FROM python:3.11-slim

# Install minimal tools and awscli
RUN apt-get update \
  && apt-get install -y --no-install-recommends zip unzip curl \
  && pip install --no-cache-dir awscli \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /github/workspace
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
